---
title: "Testing Mdls"
output: html_document
---

```{r}


# TELECOMS DATA # 

library(tidyverse)
library(car)
library(faraway)


prices = read.csv("prices.csv")
securities = read.csv("securities.csv")
fund = read.csv("fundamentals.csv")
psa = read.csv("prices-split-adjusted.csv")



# Ticker symbols of telecommunications companies
TeleSymbol = securities[securities$GICS.Sector == 
                          "Telecommunications Services", "Ticker.symbol"]


# subset dataset to Tele Companies

teleprices = psa[psa$symbol %in% c(TeleSymbol),]

row.names(teleprices) = NULL

# teleprices$year = substr(teleprices$date, start = 1, stop = 4)


mdlT = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "T",])

mdlCTL = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "CTL",])

mdlFTR = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "FTR",])

mdlLVLT = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "LVLT",])

mdlVZ = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "VZ",])

```

```{r}

library(lubridate)

# putting 2012 yearly of fund in daily 2013 psa rows

teleprices$date = ymd(teleprices$date)
teleprices$year = year(teleprices$date)-1

teleprices = teleprices[teleprices$year %in% unique(fund$For.Year),]
fundminus = select(fund,-c("X","Ticker.Symbol","Period.Ending"))

# for loops to add all columns of fund into teleprices

for(i in TeleSymbol){
        ex = fund[fund$Ticker.Symbol == i,]
        for(j in unique(ex$For.Year)){
                for(k in names(fundminus)){
                        if(k != "For.Year"){
                teleprices[(teleprices$symbol == i) & (teleprices$year == j), 
                           k] = ex[ex$For.Year == j,k]
                        }
                }
        }
}




```

```{r}
# running regression on all variables

xnames = paste0(names(select(teleprices,-c("close","symbol","date","year"))),
                collapse = "+")
fma = as.formula(paste("close ~", paste(xnames)))
mdlALL = lm(fma, teleprices[teleprices$symbol == "T",])


```

TESTING MDLS


```{r}

# MDL including every variable

summary(mdlALL)


# MDL excluding all NA's , low and high regressors

mdlfit1 = lm(close~open+volume+Accounts.Payable+Accounts.Receivable+Add.l.income.expense.items,data = teleprices)

summary(mdlfit1)



# refit model - removing Accounts receivable as its p-value exceeds alpha = 0.05 

mdlfit2 = lm(close~open+volume+Accounts.Receivable+Add.l.income.expense.items,teleprices[teleprices$symbol == "T",])

summary(mdlfit2)

test_mdl = lm(close ~ volume + Net.Cash.Flow,data = teleprices[teleprices$symbol == "T",])
summary(test_mdl)

#volume
#Capital.Surplus
#Liabilities
#Gross.Margin

#teleprices$Net.Cash.Flow




Tester = teleprices[teleprices$symbol == "T",]
Tester 

# MDL

full_mdl = lm(close ~ volume + Capital.Surplus + Gross.Margin + Liabilities ,teleprices[teleprices$symbol == "T",])

step(full_mdl)

# Ran a stepwise regression the current model
# Results: no changes to the model 

summary(full_mdl)

# All 4 regressors are less than signicant with p-values less than 0.05 percent (testing @ alpha level = 0.05)
# Having all 4 regressors included indicates 66.4% of the errors are explained in the model





# Residuals vS Fitted plot

plot(full_mdl,which=1)

# Fitted plot residual shows a potential problem with constant variance with the model as the model fans outwards further down the fitted values






# NORMAL Q-Q

plot(full_mdl,which=2)

# From Normal Plot we see that majority of the points lie near or within the normal line however on the right side of the graph we see an unusual pattern where the points start to stray above the normal line indicating either the distribution is right skewed or an increase occurance of potiential outliers


# Scale=Location

plot(full_mdl,which=3)

# this graph provides similar context as first plot but results show that standardizing the residuals helps improve the constant variance 




# Cooks Distance

plot(full_mdl,which=4)

# influential
cooks = cooks.distance(full_mdl) 
head(sort(cooks,decreasing = TRUE))
sort(cooks>1,decreasing=TRUE) 
# all false

# there are no influential points (no points in cooks.distance > 1)





# Residual vs Leverage Plot

plot(full_mdl,which=5)

# We notice in this graph that no points exceed the Cook's distance meaning 

# diagonal 
influ = influence(full_mdl)

# leverage 

sorting = sort(influ$hat[influ$hat>(2*4)/nrow(Tester)],decreasing = TRUE)
count = length(sorting)

# we identified that there are 38 influential points in the data set that are potientiall affecting the slope



vif(full_mdl) 

# using vif = 10 as the indication of multicollinearity , we do not see any of the regressors graeter than 10 therefore there is no issues of multicollinearity 










```

