---
title: "nystocks"
output: pdf_document
---

```{r}
# https://www.diva-portal.org/smash/get/diva2:692167/FULLTEXT01.pdf

# NY STOCK for multiple regression

prices = read.csv("prices.csv")
securities = read.csv("securities.csv")
fund = read.csv("fundamentals.csv")
psa = read.csv("prices-split-adjusted.csv")

# Ticker symbols of tech companies

TechSymbol = securities[securities$GICS.Sector == 
                          "Information Technology", "Ticker.symbol"]

# subset dataset to Nvidia data only
nvdaprices = psa[psa$symbol=="NVDA",]

# subset dataset to Tech Companies

techprices = psa[psa$symbol %in% c(TechSymbol),]

row.names(techprices) = NULL

row.names(nvdaprices) = NULL

# removes NAs
# fund[complete.cases(fund),]


#difference = techprices$difference
#close = techprices$close
#open = techprices$open

# techprices$difference = 0

#for(i in 1:nrow(techprices))
#{
#  techprices$difference[i] = (techprices$close[i]/techprices$open[i])
#  if(techprices$difference[i] > 1)
#  {
#    techprices$difference[i] = techprices$difference[i] - 1
#  }
#  else if(techprices$difference[i] < 1)
#  {
  #  techprices$difference[i] = techprices$difference[i] - 1
 # }
#}

#for( i in unique(techprices$symbol)){
 # print(techprices[techprices$symbol == i,])
#}

#techprices$rollingdiff = 0

#for( i in unique(techprices$symbol)){
#  for(j in 1:nrow(techprices[techprices$symbol == i,])-1){
    
    #if(j == 1){
   #   techprices[techprices$symbol == i, "rollingdiff"][j] = 
   #     techprices[techprices$symbol == i, "difference"][j]
   # }
    #else{
      #techprices[techprices$symbol == i, "rollingdiff"][j] = 
      #techprices[techprices$symbol == i, "rollingdiff"][j-1] +
      #[techprices$symbol == i, "difference"][j]
    #}
    
    
  #}
  
#}

#for(i in unique(securities$GICS.Sector)){
  #print(i)
  #print(securities[securities$GICS.Sector == i, "Ticker.symbol"])
#}

```

```{r}
mdl = lm(close~open+low+high+volume, data = nvdaprices)
logmdl = lm(log(close)~open+low+high+volume, data = nvdaprices)
y2mdl = lm(close^2~open+low+high+volume,nvdaprices)
sqrtymdl = lm(sqrt(close)~open+low+high+volume,nvdaprices)

# best transformation, highest correlation and fixed constant variance
# more data on the left side of residuals vs fitted
# normality is adequate
# linearity met on 

sqrtmdl = lm(sqrt(close)~sqrt(open) + sqrt(low) +sqrt(high) +sqrt(volume), 
             nvdaprices)

# linearity met as points are situated around zero
plot(sqrtmdl, which = 1)

# normality is adequate slight positive skew at the right tail and slight
# negative skew on the left tail
plot(sqrtmdl, which = 2)

# constant variance met if more data points are on the right
plot(sqrtmdl, which = 3)

# point 1760 is outside cook's distance thus is a influential point
# point 1729 is far on the right thus is potentially a leverage point
plot(sqrtmdl, which = 5)

library(faraway)
influ = influence(sqrtmdl)
head(sort(influ$hat, decreasing = TRUE))

cooks = cooks.distance(sqrtmdl)
head(sort(cooks,decreasing = TRUE))

# Point 1760 has the highest cook's distance and greater than 1 thus influential
# Point 1729 and 1760 has the highest influence thus leverage point

library(dplyr)
```

