---
title: "Telecommunications"
output: pdf_document
---

```{r}
prices = read.csv("prices.csv")
securities = read.csv("securities.csv")
fund = read.csv("fundamentals.csv")
psa = read.csv("prices-split-adjusted.csv")

# Ticker symbols of telecommunications companies
TeleSymbol = securities[securities$GICS.Sector == 
                          "Telecommunications Services", "Ticker.symbol"]

# subset dataset to Tele Companies

teleprices = psa[psa$symbol %in% c(TeleSymbol),]

row.names(teleprices) = NULL

# teleprices$year = substr(teleprices$date, start = 1, stop = 4)


mdlT = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "T",])

mdlCTL = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "CTL",])

mdlFTR = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "FTR",])

mdlLVLT = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "LVLT",])

mdlVZ = lm(close ~ open + low + high + volume, 
           data = teleprices[teleprices$symbol == "VZ",])



```

```{r}
library(lubridate)

# putting 2012 yearly of fund in daily 2013 psa rows

teleprices$date = ymd(teleprices$date)
teleprices$year = year(teleprices$date)-1

teleprices = teleprices[teleprices$year %in% unique(fund$For.Year),]
fundminus = select(fund,-c("X","Ticker.Symbol","Period.Ending"))

# for loops to add all columns of fund into teleprices

for(i in TeleSymbol){
        ex = fund[fund$Ticker.Symbol == i,]
        for(j in unique(ex$For.Year)){
                for(k in names(fundminus)){
                        if(k != "For.Year"){
                teleprices[(teleprices$symbol == i) & (teleprices$year == j), 
                           k] = ex[ex$For.Year == j,k]
                        }
                }
        }
}



```

```{r}
# running regression on all variables

xnames = paste0(names(select(teleprices,-c("close","symbol","date","year"))),
                collapse = "+")
fma = as.formula(paste("close ~", paste(xnames)))
mdlALL = lm(fma, teleprices[teleprices$symbol == "T",])

```


```{r}
# Making difference column

teleprices$difference = 0

for(i in 1:nrow(teleprices))
{
  teleprices$difference[i] = (teleprices$close[i]/teleprices$open[i])
  if(teleprices$difference[i] > 1)
  {
    teleprices$difference[i] = teleprices$difference[i] - 1
  }
  else if(teleprices$difference[i] < 1)
  {
    teleprices$difference[i] = teleprices$difference[i] - 1
  }
}
```


```{r}
# Added Variable Plots for models

library(car)

avPlots(mdlT)
avPlots(mdlCTL)
avPlots(mdlFTR)
avPlots(mdlLVLT)
avPlots(mdlVZ)


```



```{r}
# Plots to see how correlated each variable are to each other

par(mfrow = c(2,4))

plot(teleprices[teleprices$symbol=="T","open"],
     teleprices[teleprices$symbol=="T","close"], xlab = "Open Price", 
     ylab = "Close Price", main = "AT&T Inc Open vs Close")

plot(teleprices[teleprices$symbol=="T","low"],
     teleprices[teleprices$symbol=="T","close"], xlab = "Low Price", 
     ylab = "Close Price", main = "AT&T Inc Low vs Close")

plot(teleprices[teleprices$symbol=="T","high"],
     teleprices[teleprices$symbol=="T","close"], xlab = "High Price", 
     ylab = "Close Price", main = "AT&T Inc High vs Close")

plot(teleprices[teleprices$symbol=="T","volume"],
     teleprices[teleprices$symbol=="T","close"], xlab = "Volume", 
     ylab = "Close Price", main = "AT&T Inc Volume vs Close")

plot(teleprices[teleprices$symbol=="T","high"],
     teleprices[teleprices$symbol=="T","low"], xlab = "Volume", 
     ylab = "Close Price", main = "AT&T Inc Volume vs Close")

plot(teleprices[teleprices$symbol=="T","open"],
     teleprices[teleprices$symbol=="T","low"], xlab = "Volume", 
     ylab = "Close Price", main = "AT&T Inc Volume vs Close")

plot(teleprices[teleprices$symbol=="T","open"],
     teleprices[teleprices$symbol=="T","high"], xlab = "Volume", 
     ylab = "Close Price", main = "AT&T Inc Volume vs Close")

plot(teleprices[teleprices$symbol=="T","volume"],
     teleprices[teleprices$symbol=="T","high"], xlab = "Volume", 
     ylab = "Close Price", main = "AT&T Inc Volume vs Close")
```


```{r}
# Boxplots of each companies different columns

library(reshape2)
library(tidyverse)

df = melt(teleprices, id.vars = c("open","close","low","high","volume"),
          measure.vars = c("symbol"))

(p1 = ggplot(df, aes(value,close, fill = value)) + geom_boxplot()+ 
                labs(x = "Companies",y = "Close Price",
        title = "Boxplot of All Telecommunication Services and Close Price"))

(p2 = ggplot(df, aes(value,open, fill = value)) + geom_boxplot()+ 
                labs(x = "Companies",y = "Open Price",
        title = "Boxplot of All Telecommunication Services and Open Price"))

(p3 = ggplot(df, aes(value,low, fill = value)) + geom_boxplot()+ 
                labs(x = "Companies",y = "Low Price",
        title = "Boxplot of All Telecommunication Services and Low Price"))

(p4 = ggplot(df, aes(value,high, fill = value)) + geom_boxplot()+ 
                labs(x = "Companies",y = "High Price",
        title = "Boxplot of All Telecommunication Services and High Price"))

(p5 = ggplot(df, aes(value,volume, fill = value)) + geom_boxplot()+ 
                labs(x = "Companies",y = "Volume",
        title = "Boxplot of All Telecommunication Services and Volume")+ 
                coord_cartesian(ylim = c(0,1e+08)))
```


```{r}
# Cross Validation

library(caret)

set.seed(123)

df = teleprices[teleprices$symbol=="T",]

nsamp=ceiling(0.8*length(df$close))
training_samps=sample(c(1:length(df$close)),
                      nsamp)
training_samps=sort(training_samps)
train_data  <- df[training_samps, ]
test_data <-   df[-training_samps, ]


train.lm <- lm(close ~ open + low + high + volume, 
               data = df)

summary(train.lm)

preds <- predict(train.lm,test_data)

plot(test_data$close,preds)
abline(c(0,1))

R.sq = R2(preds, test_data$close)
RMSPE = RMSE(preds, test_data$close)
MAPE = MAE(preds, test_data$close)
NSE=1-RMSPE^2/var(test_data$close)
print(c(R.sq,RMSPE,MAPE,NSE))

set.seed(123)

for(i in 1:10){

nsamp=ceiling(0.8*length(df$close))
training_samps=sample(c(1:length(df$close)),
                      nsamp)
training_samps=sort(training_samps)
train_data  <- df[training_samps, ]
test_data <-   df[-training_samps, ]


train.lm <- lm(close ~ open + low + high + volume, 
               data = df)

summary(train.lm)

preds <- predict(train.lm,test_data)

plot(test_data$close,preds)
abline(c(0,1))

R.sq = R2(preds, test_data$close)
RMSPE = RMSE(preds, test_data$close)
MAPE = MAE(preds, test_data$close)
NSE=1-RMSPE^2/var(test_data$close)
print(c(R.sq,RMSPE,MAPE,NSE))        
}
```

