```{r}
# NY STOCK for multiple regression
library(dplyr)
library(car)

library(lubridate)
prices = read.csv("prices.csv")
securities = read.csv("securities.csv")
fund = read.csv("fundamentals.csv")
psa = read.csv("prices-split-adjusted.csv")


# focus mainly on psa dataset because it accounts for price splits.
psa$difference = 0
difference = psa$difference
close = psa$close
open = psa$open

for(i in 1:nrow(psa))
{
  difference[i] = (close[i]/open[i])
  if(difference[i] > 1)
  {
    difference[i] = difference[i] - 1
  }
  else if(difference[i] < 1)
  {
    difference[i] = difference[i] - 1
  }
}

# stock return for a certain year


telecommunications = securities %>% 
  filter(GICS.Sector == "Telecommunications Services")


bind = psa %>% filter(psa$symbol == "T" |psa$symbol == "CTL" | psa$symbol =="FTR"| psa$symbol == "LVLT"| psa$symbol == "VZ")


for(i in 1:nrow(bind))
{
  bind$difference[i] = (bind$close[i]/bind$open[i])
  if(bind$difference[i] > 1)
  {
    bind$difference[i] = bind$difference[i] - 1
  }
  else if(bind$difference[i] < 1)
  {
    bind$difference[i] = bind$difference[i] - 1
  }
}


fundtemp = fund %>% 
  filter(Ticker.Symbol == "T" | Ticker.Symbol == "CTL"|Ticker.Symbol == "FTR" | Ticker.Symbol == "LVLT" | Ticker.Symbol == "VZ")



ctl = bind[bind$symbol == "CTL",]
atnt = bind[bind$symbol == "T",]
ftr = bind[bind$symbol == "FTR",]
vz = bind[bind$symbol == "VZ",]
lvlt = bind[bind$symbol == "LVLT",]

# CHANGING CLASS OF DATES FROM DATASET TO CLASS: DATE FROM CHARACTERS

#date = as.Date(bind[,1])
#bind = cbind(date,bind)
#bind = subset(bind, select = -c(2))



#Period.Ending = as.Date(fundtemp[,3])
#fundtemp = cbind(Period.Ending, fundtemp)
#fundtemp = subset(fundtemp, select = -c(4))


# filter years in bind from 2013-2016
bind = bind %>% 
  filter(date > "2013-01-01" & date < "2016-12-31")

year(bind$date[1])

# rename fundtemp ticker.symbol to symbol to match bind
names(fundtemp)[names(fundtemp) == "Ticker.Symbol"] = "symbol"

# now use for loop to combine datasets
new = 0
for(i in 1:5040)
{
  if(bind$symbol[i] == "CTL" & year(bind$date[i]) == "2013")
  {
    new = cbind(bind[i,], fundtemp[1,])
  }
}

```




```{r}
fundminus = select(fund,-c("X","Ticker.Symbol","Period.Ending"))

TeleSymbol = securities[securities$GICS.Sector == 
                          "Telecommunications Services", "Ticker.symbol"]
teleprices = psa[psa$symbol %in% c(TeleSymbol),]
teleprices = teleprices[teleprices$year %in% unique(fund$For.Year),]


for(i in bind){
        ex = fund[fund$Ticker.Symbol == i,]
        for(j in unique(ex$For.Year)){
                for(k in names(fundminus)){
                        if(k != "For.Year"){
                        teleprices[(teleprices$symbol == i) & (teleprices$year == j), 
                           k] = ex[ex$For.Year == j,k]
                        }
                }
        }
}

```

